### ISSUE TITLE
why i can't build openGP.lib

### ISSUE THREAD

**Issue by RenFeiTemp** [OpenGP/OpenGP#21]
win 10 with vs2015

**Comment by ialhashim** [comment]
There is an issue with the CMake configuration. The generated solution includes two OpenGP projects (maybe due to header/non-header?). When removing the one that does not point to 'src/OpenGP' the library will build. 

As a temporary solution try this and if you get a chance to fix it from the CMake configuration we are happy to accept your pull.

**Comment by RenFeiTemp** [comment]
thanks,i had built openGP.lib by altering  the CMakeList.txt like this:
if(UNIX)
    add_library(OpenGP SHARED ${SOURCES} ${HEADERS})
    target_link_libraries(OpenGP ${LIBRARIES_})
elseif(WIN32)
    
    add_library(OpenGP_1 STATIC ${SOURCES} ${HEADERS})
    target_link_libraries(OpenGP_1 ${LIBRARIES_})
endif()

#--- "make install" (always install source as well for headeronly support)
install(TARGETS OpenGP DESTINATION lib/)

#--- It's a C++ library
set_target_properties(OpenGP_1 PROPERTIES LINKER_LANGUAGE CXX)
#--- Set the library version
set_target_properties(OpenGP_1 PROPERTIES VERSION 1.0)

then renamed from openGP_1.lib to oprnGP.lib

**Comment by taiya** [comment]
Hi there, this repo was mostly when I was teaching at Victoria, and as the rendering backend of research projects. As I have moved to ML, I am not maintaining it (as you can tell). That said, feel free to send a pull request with changes!
